'use strict';var dataBaseName="AudioPlayerBrianChen",objectStorName="AudioStore",audio=document.getElementById("audioPlayer"),currentAudioName="",isInRPState=!1;
const importMenu=document.getElementById("importMenu"),importSubMenu=document.getElementById("importSubMenu"),exportMenu=document.getElementById("exportMenu"),exportSubMenu=document.getElementById("exportSubMenu"),debugMenu=document.getElementById("debugMenu"),debugSubMenu=document.getElementById("debugSubMenu"),helpMenu=document.getElementById("helpMenu"),helpSubMenu=document.getElementById("helpSubMenu");var intervalID=null,rpTimePointStart=-1,rpTimePointEnd=-1;const languageToggle=document.getElementById("languageToggle");
var isEnglish=!0;
const translations={Import:"\u5bfc\u5165","Import an audio file":"\u5bfc\u5165\u4e00\u4e2a\u97f3\u9891\u6587\u4ef6",Export:"\u5bfc\u51fa","Export a repeating record file":"\u5bfc\u51fa\u4e00\u4e2a\u590d\u8bfb\u8bb0\u5f55\u6587\u4ef6",Debug:"\u8c03\u8bd5","Console: read all data":"\u63a7\u5236\u53f0\uff1a\u8bfb\u53d6\u6240\u6709\u6570\u636e","Console: delete all data":"\u63a7\u5236\u53f0\uff1a\u5220\u9664\u6240\u6709\u6570\u636e","Update play list":"\u66f4\u65b0\u64ad\u653e\u5217\u8868",Help:"\u5e2e\u52a9",
Tutorial:"\u6559\u7a0b","Continue play":"\u7ee7\u7eed\u64ad\u653e","Repeating start":"\u590d\u8bfb\u8d77\u70b9","Repeating end":"\u590d\u8bfb\u7ec8\u70b9","Add repeating":"\u6dfb\u52a0\u590d\u8bfb","Reset play":"\u91cd\u7f6e\u64ad\u653e","Audio library":"\u97f3\u9891\u5e93","Repeating list":"\u590d\u8bfb\u5217\u8868",Delete:"\u5220\u9664","All rights reserved":"\u7248\u6743\u6240\u6709","Kunniaa Voice Repeater":"\u8363\u8000\u8bed\u97f3\u590d\u8bfb\u673a",Version:"\u7248\u672c","Update date":"\u66f4\u65b0\u65e5\u671f"};
languageToggle.addEventListener("click",function(){isEnglish=!isEnglish;languageToggle.textContent=isEnglish?"\u4e2d\u6587":"EN";document.querySelectorAll("[data-translate]").forEach(a=>{const b=a.getAttribute("data-translate");a.textContent=isEnglish?b:translations[b]})});audio.addEventListener("play",()=>{setButtonState("btnCntPlay",!1);setButtonState("btnRPSart",!0);setButtonState("btnRPEnd",!1);setButtonState("btnRPAdd",!1);setButtonState("btnReset",!1)});
audio.addEventListener("ended",()=>{setButtonState("btnCntPlay",!0);setButtonState("btnRPSart",!1);setButtonState("btnRPEnd",!1);setButtonState("btnRPAdd",!1);setButtonState("btnReset",!1)});audio.addEventListener("pause",()=>{setButtonState("btnCntPlay",!0);setButtonState("btnRPSart",!1);setButtonState("btnRPEnd",!1);setButtonState("btnRPAdd",!1);setButtonState("btnReset",!1)});audio.addEventListener("mousedown",function(a){isInRPState&&(a.preventDefault(),a.stopPropagation())},!0);
audio.addEventListener("click",function(a){isInRPState&&(a.preventDefault(),a.stopPropagation())},!0);document.addEventListener("keydown",a=>{a=a.key;"ArrowLeft"==a?--audio.currentTime:"ArrowRight"==a&&(audio.currentTime+=1)},!1);importMenu.addEventListener("mouseenter",()=>{importSubMenu.classList.remove("hidden")});importMenu.addEventListener("mouseleave",a=>{"importSubMenu"!=a.target.id&&importSubMenu.classList.add("hidden")});importSubMenu.addEventListener("mouseleave",()=>{importSubMenu.classList.add("hidden")});
importSubMenu.addEventListener("click",()=>{importSubMenu.classList.add("hidden")});exportMenu.addEventListener("mouseenter",()=>{exportSubMenu.classList.remove("hidden")});exportMenu.addEventListener("mouseleave",a=>{"exportSubMenu"!=a.target.id&&exportSubMenu.classList.add("hidden")});exportSubMenu.addEventListener("mouseleave",()=>{exportSubMenu.classList.add("hidden")});exportSubMenu.addEventListener("click",()=>{exportSubMenu.classList.add("hidden")});
debugMenu.addEventListener("mouseenter",()=>{debugSubMenu.classList.remove("hidden")});debugMenu.addEventListener("mouseleave",a=>{"debugSubMenu"!=a.target.id&&debugSubMenu.classList.add("hidden")});debugSubMenu.addEventListener("mouseleave",()=>{debugSubMenu.classList.add("hidden")});debugSubMenu.addEventListener("click",()=>{debugSubMenu.classList.add("hidden")});helpMenu.addEventListener("mouseenter",()=>{helpSubMenu.classList.remove("hidden")});
helpMenu.addEventListener("mouseleave",a=>{"debugSubMenu"!=a.target.id&&helpSubMenu.classList.add("hidden")});helpSubMenu.addEventListener("mouseleave",()=>{helpSubMenu.classList.add("hidden")});helpSubMenu.addEventListener("click",()=>{helpSubMenu.classList.add("hidden")});const waveSurfer=WaveSurfer.create({container:document.getElementById("waveSurfer"),waveColor:"rgb(200, 0, 200)",progressColor:"rgb(100, 0, 100)",normalize:!0,media:audio});
waveSurfer.on("ready",function(){document.getElementById("placeholderWaveform").style.display="none"});
function exportRPFile(){let a=document.createElement("div");a.className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full flex items-center justify-center";a.innerHTML='\n                <div class="bg-white p-5 rounded-lg shadow-xl w-96">\n                    <span class="text-base font-bold mb-4">\u9009\u62e9\u8981\u5bfc\u51fa\u7684\u590d\u8bfb\u8bb0\u5f55</span>\n                    <span class="text-sm mb-4">(\u5176\u4ed6\u97f3\u9891\u65e0\u590d\u8bfb\u8bb0\u5f55)</span>\n                    <div id="rpFileList" class="mb-4 max-h-60 overflow-y-auto"></div>\n                    <div class="flex justify-end">\n                        <button id="cancelExport" class="mr-2 px-4 py-2 bg-gray-300 text-gray-800 rounded hover:bg-gray-400">\u53d6\u6d88</button>\n                        <button id="confirmExport" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">\u5bfc\u51fa</button>\n                    </div>\n                </div>\n            ';document.body.appendChild(a);
indexedDB.open(dataBaseName,1).onsuccess=function(b){b.target.result.transaction([objectStorName],"readonly").objectStore(objectStorName).getAllKeys().onsuccess=function(c){c=c.target.result;let e=document.getElementById("rpFileList");c.forEach(function(g){if(g.endsWith(".rp")){let d=document.createElement("div");d.innerHTML=`
                                <label class="flex items-center">
                                    <input type="radio" name="rpFile" value="${g}" class="mr-2">
                                    ${g}
                                </label>
                            `;e.appendChild(d)}})}};document.getElementById("cancelExport").addEventListener("click",function(){document.body.removeChild(a)});document.getElementById("confirmExport").addEventListener("click",function(){let b=document.querySelector('input[name="rpFile"]:checked');if(b){let c=b.value;indexedDB.open(dataBaseName,1).onsuccess=function(e){e.target.result.transaction([objectStorName],"readonly").objectStore(objectStorName).get(c).onsuccess=function(g){g=new Blob([JSON.stringify(g.target.result,
null,2)],{type:"text/plain"});g=URL.createObjectURL(g);let d=document.createElement("a");d.href=g;d.download=c+".txt";document.body.appendChild(d);d.click();document.body.removeChild(d);URL.revokeObjectURL(g)}};document.body.removeChild(a)}else alert("\u8bf7\u9009\u62e9\u4e00\u4e2a\u6587\u4ef6")})}function disableAudioControl(){isInRPState=!0;audio.classList.add("pointer-events-none")}function enableAudioControl(){isInRPState=!1;audio.classList.remove("pointer-events-none")}
function setButtonState(a,b){a=document.getElementById(`${a}`);a.disabled=!b;a.classList.toggle("opacity-50",!b);a.classList.toggle("cursor-not-allowed",!b)}function setButtonRPColor(a,b){a=document.getElementById(`${a}`);b?(a.classList.remove("bg-blue-500"),a.classList.add("bg-green-500")):(a.classList.remove("bg-green-500"),a.classList.add("bg-blue-500"))}
function cntPlayAudio(a){0==audio.readyState?alert("\u8bf7\u5148\u52a0\u8f7d\u97f3\u9891"):a.disabled||(null!=intervalID&&(window.clearInterval(intervalID),intervalID=null,rpTimePointEnd=rpTimePointStart=-1),isInRPState&&enableAudioControl(),audio.play(),setButtonState("btnCntPlay",!1),setButtonState("btnRPSart",!0),setButtonState("btnRPEnd",!1),setButtonState("btnRPAdd",!1),setButtonState("btnReset",!1),setButtonRPColor("btnRPSart",!1),setButtonRPColor("btnRPEnd",!1))}
function recordRPStart(a){0==audio.readyState?alert("\u8bf7\u5148\u52a0\u8f7d\u97f3\u9891"):a.disabled||(rpTimePointStart=audio.currentTime,disableAudioControl(),setButtonState("btnCntPlay",!1),setButtonState("btnRPSart",!1),setButtonState("btnRPEnd",!0),setButtonState("btnRPAdd",!1),setButtonState("btnReset",!0),setButtonRPColor("btnRPSart",!0),setButtonRPColor("btnRPEnd",!1))}
function recordRPEnd(a){0==audio.readyState?alert("\u8bf7\u5148\u52a0\u8f7d\u97f3\u9891"):a.disabled||(rpTimePointEnd=audio.currentTime,rpTimePointEnd<rpTimePointStart?alert("\u590d\u8bfb\u7ec8\u70b9\u65f6\u95f4\u70b9\u5c0f\u4e8e\u590d\u8bfb\u8d77\u70b9\u65f6\u95f4\u70b9\uff0c\u65e0\u6548\uff0c\u8bf7\u91cd\u9009\u590d\u8bfb\u7ec8\u70b9\u3002"):(rpTimePointEnd=audio.currentTime,audio.currentTime=rpTimePointStart,audio.play(),intervalID=window.setInterval(function(){audio.currentTime>=rpTimePointEnd?
audio.currentTime=rpTimePointStart:audio.currentTime<=rpTimePointStart&&(audio.currentTime=rpTimePointStart)},0),setButtonState("btnCntPlay",!1),setButtonState("btnRPSart",!1),setButtonState("btnRPEnd",!1),setButtonState("btnRPAdd",!0),setButtonState("btnReset",!0),setButtonRPColor("btnRPSart",!0),setButtonRPColor("btnRPEnd",!0)))}
function updateOrAddToIndexedDB(a,b){return new Promise((c,e)=>{console.log("\u8fdb\u5165updateOrAddToIndexedDB");let g=indexedDB.open(dataBaseName,1),d;g.onsuccess=function(f){d=f.target.result;f=d.transaction(objectStorName,"readwrite");let k=f.objectStore(objectStorName),l=k.get(a);l.onsuccess=function(h){void 0!==h.target.result?(h=h.target.result,0===Object.keys(h).length?h=[b]:(h=Array.isArray(h)?h:[h],h.push(b)),h.sort((n,m)=>n[0]-m[0]),h=k.put(h,a),h.onsuccess=function(){c("\u66f4\u65b0\u6210\u529f")},
h.onerror=function(){e("\u66f4\u65b0\u5931\u8d25\uff1a"+this.error)}):(h=k.put([b],a),h.onsuccess=function(){c("\u66f4\u65b0\u6210\u529f")},h.onerror=function(){e("\u66f4\u65b0\u5931\u8d25\uff1a"+this.error)})};l.onerror=function(){e("\u83b7\u53d6\u952e\u503c\u5931\u8d25\uff1a"+this.error)};f.oncomplete=function(){d&&d.close()}};g.onerror=function(){console.error("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25\uff1a",this.error);e("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25\uff1a"+this.error)}})}
function addRP(a){0==audio.readyState?alert("\u8bf7\u5148\u52a0\u8f7d\u97f3\u9891"):a.disabled||(a=[rpTimePointStart,rpTimePointEnd],console.log(""+audio.name+","+rpTimePointStart+","+rpTimePointEnd),updateOrAddToIndexedDB(currentAudioName+".rp",a),updateRpList(currentAudioName),setButtonState("btnCntPlay",!0),setButtonState("btnRPSart",!1),setButtonState("btnRPEnd",!1),setButtonState("btnRPAdd",!1),setButtonState("btnReset",!1),setButtonRPColor("btnRPSart",!0),setButtonRPColor("btnRPEnd",!0))}
function resetAudioPlay(a){0==audio.readyState?alert("\u8bf7\u5148\u52a0\u8f7d\u97f3\u9891"):a.disabled||(null!=intervalID&&(window.clearInterval(intervalID),intervalID=null),document.getElementById("rpList").querySelectorAll("li").forEach(b=>b.classList.remove("bg-green-200","text-green-800")),enableAudioControl(),audio.currentTime=rpTimePointEnd,audio.play(),rpTimePointEnd=rpTimePointStart=-1,setButtonState("btnCntPlay",!1),setButtonState("btnRPSart",!0),setButtonState("btnRPEnd",!1),setButtonState("btnRPAdd",
!1),setButtonState("btnReset",!1),setButtonRPColor("btnRPSart",!1),setButtonRPColor("btnRPEnd",!1))}
function saveAudioToDataBase(){let a=!1,b=document.getElementById("fileInput");b.addEventListener("change",function(){if(!a){let c=b.files[0],e=new FileReader;e.onload=function(){let g=this.result,d=indexedDB.open(dataBaseName,1);d.onupgradeneed=function(f){f=f.target.result;f.objectStoreNames.contains(objectStorName)||f.createObjectStore(objectStorName)};d.onsuccess=function(f){let k=f.target.result;f=k.transaction(objectStorName,"readwrite").objectStore(objectStorName).add(g,c.name);f.onsuccess=
function(l){k.close();console.log("\u97f3\u9891\u5df2\u5b58\u50a8\u5230\u6570\u636e\u5e93");updatePlayList()};f.onerror=function(l){k.close();alert("\u97f3\u9891\u5b58\u50a8\u5931\u8d25\uff1a"+this.error);console.log("\u97f3\u9891\u5b58\u50a8\u5931\u8d25\uff1a",this.error)};k.close()};d.onerror=function(f){f.target.result.close();alert("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25\uff1a"+this.error);console.log("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25\uff1a",this.error)}};e.readAsArrayBuffer(c);
a=!0}});b.click()}
async function readAllDataBase(){for(var a=await indexedDB.databases(),b=0;b<a.length;b++)console.log("i="+b),console.log("database name = "+a[b].name),indexedDB.open(a[b].name,1).onsuccess=function(c){c=c.target.result;for(var e=c.objectStoreNames,g=0;g<e.length;g++){var d=e[g];console.log("    objectStoreName="+d);c.transaction(d,"readonly").objectStore(d).getAllKeys().onsuccess=function(f){f=f.target.result;for(var k=0;k<f.length;k++)console.log("        keyName="+f[k])}}c.close()}}
async function rmAllDataBase(){for(var a=await indexedDB.databases(),b=0;b<a.length;b++){console.log("\u5220\u9664"+b+":"+a[b].name);const c=window.indexedDB.deleteDatabase(a[b].name);c.onerror=e=>{console.log("Error deleting database.");location.reload()};c.onsuccess=e=>{console.log("Database deleted successfully");location.reload();console.log(e.result)}}location.reload()}
function readRPList(a){var b=indexedDB.open(dataBaseName,1);b.onerror=function(c){console.log("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25")};b.onupgradeneed=function(c){c=c.target.result;c.objectStoreNames.contains(objectStorName)||c.createObjectStore(objectStorName)};b.onsuccess=function(c){c=event.target.result.transaction([objectStorName],"readonly");c.objectStore(objectStorName).get(a+".rp").onsuccess=function(e){e=e.target.result;let g=document.getElementById("rpList");e&&0<e.length&&e.forEach(function(d){let f=
document.createElement("li");f.classList.add("py-2","px-3","hover:bg-gray-300","cursor-pointer","transition","duration-100");var k=d[0],l=d[1];let h=Math.floor(k/60);k=(k%60).toFixed(2);let n=Math.floor(l/60);l=(l%60).toFixed(2);f.textContent=`${h}:${k} - ${n}:${l}`;f.dataset.startTime=d[0];f.dataset.endTime=d[1];f.addEventListener("click",function(){disableAudioControl();rpTimePointStart=d[0];rpTimePointEnd=d[1];g.querySelectorAll("li").forEach(m=>m.classList.remove("bg-green-200","text-green-800"));
this.classList.add("bg-green-200","text-green-800");null!=intervalID&&(window.clearInterval(intervalID),intervalID=null);intervalID=window.setInterval(function(){audio.currentTime>=rpTimePointEnd?audio.currentTime=rpTimePointStart:audio.currentTime<=rpTimePointStart&&(audio.currentTime=rpTimePointStart)},0);setButtonState("btnCntPlay",!1);setButtonState("btnRPSart",!1);setButtonState("btnRPEnd",!1);setButtonState("btnRPAdd",!1);setButtonState("btnReset",!0);setButtonRPColor("btnRPSart",!0);setButtonRPColor("btnRPEnd",
!0)});f.addEventListener("contextmenu",function(m){m.preventDefault();showContextMenuRP(m,d[0],d[1])});g.appendChild(f)})};c.onerror=function(e){console.log("\u8bfb\u53d6\u590d\u8bfb\u6570\u636e\u5931\u8d25")}};b.onerror=function(c){console.log("\u8bfb\u53d6\u590d\u8bfb\u6570\u636e\u5931\u8d25")}}
function showContextMenu(a,b){var c=document.getElementById("contextMenu");c.style.left=a.pageX+"px";c.style.top=a.pageY+"px";c.classList.remove("hidden");document.getElementById("deleteOption").onclick=function(){deleteAudioFile(b);c.classList.add("hidden")};document.addEventListener("click",function g(){c.classList.add("hidden");document.removeEventListener("click",g)})}
function deleteAudioFile(a){let b=indexedDB.open(dataBaseName,1),c;b.onsuccess=function(e){c=e.target.result;e=c.transaction([objectStorName],"readwrite").objectStore(objectStorName);let g=e.delete(a);g.onsuccess=function(d){console.log("\u6587\u4ef6\u5df2\u5220\u9664: "+a)};g.onerror=function(d){console.error("\u5220\u9664\u6587\u4ef6\u5931\u8d25: "+d.target.error)};e=e.delete(a+".rp");e.onsuccess=function(d){console.log("\u6587\u4ef6\u5df2\u5220\u9664: "+a+".rp");updatePlayList();currentAudioName===
a&&updateRpList(currentAudioName);c.close()};e.onerror=function(d){console.error("\u5220\u9664\u6587\u4ef6\u5931\u8d25: "+d.target.error);c.close()};c.close()};b.onerror=function(e){c.close();console.error("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25: "+e.target.error)}}
function showContextMenuRP(a,b,c){var e=document.getElementById("contextMenuRP");e.style.left=a.pageX+"px";e.style.top=a.pageY+"px";e.classList.remove("hidden");document.getElementById("deleteOptionRP").onclick=function(){deleteRepeatSegment(b,c);e.classList.add("hidden")};document.addEventListener("click",function d(){e.classList.add("hidden");document.removeEventListener("click",d)})}
function deleteRepeatSegment(a,b){let c=indexedDB.open(dataBaseName,1);c.onsuccess=function(e){let g=e.target.result.transaction([objectStorName],"readwrite").objectStore(objectStorName);e=g.get(currentAudioName+".rp");e.onsuccess=function(d){(d=d.target.result)&&Array.isArray(d)&&(d=d.filter(f=>!(f[0]===a&&f[1]===b)),d=g.put(d,currentAudioName+".rp"),d.onsuccess=function(){console.log("\u590d\u8bfb\u6bb5\u5df2\u5220\u9664");updateRpList(currentAudioName)},d.onerror=function(f){console.error("\u5220\u9664\u590d\u8bfb\u6bb5\u5931\u8d25: "+
f.target.error)})};e.onerror=function(d){console.error("\u83b7\u53d6\u590d\u8bfb\u6bb5\u6570\u636e\u5931\u8d25: "+d.target.error)}};c.onerror=function(e){console.error("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25: "+e.target.error)}}
function readPlayList(){var a=indexedDB.open(dataBaseName,1);a.onerror=function(b){console.log("\u6253\u5f00\u6570\u636e\u5e93\u5931\u8d25")};a.onupgradeneed=function(b){b=b.target.result;b.objectStoreNames.contains(objectStorName)||b.createObjectStore(objectStorName)};a.onsuccess=function(b){b=event.target.result.transaction([objectStorName],"readonly");b.objectStore(objectStorName).getAllKeys().onsuccess=function(c){c=c.target.result;var e=document.getElementById("playList");c.forEach(function(g){if(g.endsWith(".mp3")){var d=
document.createElement("li");d.textContent=g;d.classList.add("py-2","px-3","hover:bg-gray-300","cursor-pointer","transition","duration-100");d.addEventListener("click",function(){isInRPState?alert("\u76ee\u524d\u5728\u590d\u8bfb\u76f8\u5173\u72b6\u6001\uff0c\u5207\u6362\u8bf7\u5148\u590d\u4f4d\u91cd\u8bbe\u3002"):(currentAudioName=d.textContent,waveSurfer.stop(),readAudioAndPlay(currentAudioName),updateRpList(currentAudioName),e.querySelectorAll("li").forEach(f=>f.classList.remove("bg-blue-200","text-blue-800")),
this.classList.add("bg-blue-200","text-blue-800"))});d.addEventListener("contextmenu",function(f){f.preventDefault();showContextMenu(f,g)});e.appendChild(d)}})};b.onerror=function(c){console.log("\u8bfb\u53d6\u6570\u636e\u5931\u8d25")}}}function updatePlayList(){document.getElementById("playList").innerHTML="";readPlayList()}function updateRpList(a){document.getElementById("rpList").innerHTML="";readRPList(a)}
function readAudioAndPlay(a){let b=indexedDB.open(dataBaseName,1);b.onsuccess=function(c){c=c.target.result.transaction([objectStorName]).objectStore(objectStorName).get(a);c.onsuccess=function(e){e=new Blob([e.target.result],{type:"audio/mp3"});audioURL=URL.createObjectURL(e);waveSurfer.load(audioURL);audio.src=audioURL;currentAudioName=a;audio.play()};c.onerror=function(){console.log("\u8bfb\u53d6\u6587\u4ef6\u5931\u8d25\uff1a",this.error)}};b.onerror=function(c){console.error("Error opening database:",
c.target.error)}}window.onload=function(){updatePlayList()};